# 에러 핸들링
## 'try..catch'와 에러 핸들링
- 비동기 코드는 못잡아냄(ex: `setTimeout`).
- 스크립트가 멈추는걸 막으면서 에러에 대한 대응

### 에러 객체
- 에러 이름(`name`), 에러 내용(`message`), 현재 호출스택(`stack`) property 보유
- 필요 없으면 `catch {..}`로 걍 생략 가능(구식 브라우저는 polyfill 필요)
- `throw`는 객체가 아니라도 막 던질 수는 있음. 다만 내장 에러와 호환을 위해 `name`, `message`는 넣어주자
```js
try {
  lalala; // 변수가 정의되지 않음
} 
catch(err) {
  alert(err.name); // ReferenceError
  alert(err.message); // lalala is not defined
  alert(err.stack); // ReferenceError: lalala is not defined at ... (호출 스택)
  alert(err); // ReferenceError: lalala is not defined
}
```
### 에러 다시 던지기
- `try`문에서 예기치 않은 다른 에러가 터질 수 있기 때문에 `catch`문에선 알고 있는 에러만 처리하고 나머지는 다시 던져야됨.
```js
function readData() {
    let json = '{ "age": 30 }'; // 나이밖에 없는 불완전한 데이터

    try {
        let user = JSON.parse(json);

        if (!user.name) {
            throw new SyntaxError("불완전한 데이터: 이름 없음");
        }
        sdjflksjdlkfj();  // 예상치 못한 에러
    } 
    catch(err) {
        if (e instanceof SyntaxError) {
            alert( "JSON Error: " + e.message );
        } else {
            throw e;
        }
    }
}

try {
    readData();
} catch (e) {
    alert( "External catch got: " + e ); // 위의 예상치 못한 에러도 잡음
}
finally {
    // try -> finally or try -> catch -> finally
    // try에서 return문 때려박아도 여기로 오게됨. 함수에서도 유용할듯
}
```

## 전역 catch
`try..catch`문 밖에서 에러 발생으로 스크립트가 죽을 수도 있음
<br>이럴 때 js 호스트 환경 대다수는 자체적 에러 처리기능을 제공함

- Node.js에선 [process.on("uncaughtException")](https://nodejs.org/api/process.html#process_event_uncaughtexception)
- 브라우저 환경에선 [window.onerror](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror)

```js
<script>
  // 함수할당시 예상치 못한 에러를 해당 함수가 처리함
  /**
    message: 에러 메시지
    url: 에러가 발생한 스크립트의 URL
    line, col: 에러가 발생한 곳의 줄과 열 번호
    error: 에러 객체
  **/
  window.onerror = function(message, url, line, col, error) {
    alert(`${message}\n At ${line}:${col} of ${url}`);
  };

  function readData() {
    badFunc(); // 에러가 발생한 장소
  }

  readData();
</script>
```
근데 `window.onerror`는 죽어버린 스크립트 복구용으론 거의 사용 x. 프로그래밍 에러시 이거만으로 복구는 어렵다. 그냥 개발자 메세지용. 
<br>https://errorception.com 나 http://www.muscula.com같은 에러 로깅 관련 상용 서비스가 있음.

## 커스텀 에러와 확장
- Error 클래스를 상속받아 `instanceof`도 쓸 수 있는 에러 객체를 만들 수 있음
- Error의 `name`을 일일히 설정해주기 귀찮으면 생성자에서 `this.name = this.constructor.name`로 처리. 후에 상속받는 애들도 설정해줄 필요가 없어짐
- `catch`문에서 에러의 종류를 하나하나 조건문으로 에러 종류를 체크하기보다 wrapping exception 기법을 사용해 하나의 에러객체만 체크하면 편하다
```js
class ReadError extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = 'ReadError';
  }
}

class ValidationError extends Error { /*...*/ }
class PropertyRequiredError extends ValidationError { /* ... */ }

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError("age");
  }

  if (!user.name) {
    throw new PropertyRequiredError("name");
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError("Syntax Error", err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError("Validation Error", err);
    } else {
      throw err;
    }
  }

}

try {
  readUser('{잘못된 형식의 json}');
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Original error: SyntaxError: Unexpected token b in JSON at position 1
    alert("Original error: " + e.cause);
  } else {
    throw e;
  }
}
```